### ISSUE TITLE
Get Data

### ISSUE THREAD

**Issue by swalljasper** [geog575-spring2016/metro-transit#1]
We need to get the data for all of the counties we are doing. CSV Data can be found at
http://factfinder.census.gov/faces/nav/jsf/pages/download_center.xhtml#none

CSV Needs: Median Household Income, Race, Age, Families, Commute Time, Means of Transportation for Hennepin, Ramsey, Scott, Dakota counties.

Shapefiles for Hennepin, Ramsey, Scott, Dakota counties

Convert to topojson --> geojson

**Comment by gvriezen** [comment]
Just added the csv to the data folder. Here are all the data sets I used. Let me know if I missed anything. 

**B19013 - Median Household Income**
-- Estimate; Median household income in the past 12 months (in 2014 Inflation-adjusted dollars)
**S0101 - Age and Sex**
-- Total; Estimate; SUMMARY INDICATORS - Median age (years)
**S11101 - Household and Family Type**
-- Nonfamily household; Estimate; Total households
--Married-couple family household; Estimate; FAMILIES - Total families
--Male householder, no wife present, family household; Estimate; Total households
-- Female householder, no husband present, family household; Estimate; Total households
**B02001 - Race**
-- Estimate; Total: - White alone
-- Estimate; Total: - Black or African American alone
-- Estimate; Total: - American Indian and Alaska Native alone
-- Estimate; Total: - Asian alone
--Estimate; Total: - Native Hawaiian and Other Pacific Islander alone

_**didn't have Hispanic/Latino in dataset??**_

**B08301 - Means of Transportation**
--Estimate; Car, truck, or van:
--Estimate; Public transportation (excluding taxicab):
--Estimate; Motorcycle*\* -- _**could probably take this out**_
--Estimate; Bicycle 
-- Estimate; Walked
--Estimate; Other means
--Estimate; Worked at home **_(could also take this one out?)_**
**S0802 - Commute Time** 
-- Car, truck, or van -- drove alone; Estimate; TRAVEL TIME TO WORK - Mean travel time to work (minutes)
--Public transportation (excluding taxicab); Estimate; TRAVEL TIME TO WORK - Mean travel time to work (minutes)
